// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.PaginationRequests.CustomerPaginationRequest
{
    public partial class CustomerPaginationRequestModel : Communication.Models.ModelBase, Communication.Models.PaginationRequests.CustomerPaginationRequest.ICustomerPaginationRequestModel
    {
        public System.UInt32 PageNumber { get; set; }
        public Communication.Models.Filters.CustomerModelFilter.ICustomerModelFilterModel Filter { get; set; } = new Communication.Models.Filters.CustomerModelFilter.CustomerModelFilterModel();
    }
}