// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
using System.Linq;
using Common.Extensions.Object;
namespace Communication.Models.PaginationRequests.CustomerPaginationRequest
{
    public interface ICustomerPaginationRequestModel : Communication.Models.IModelBase, IEquatable<ICustomerPaginationRequestModel>
    {
        public System.UInt32 PageNumber { get; }
        public Communication.Models.Filters.CustomerModelFilter.ICustomerModelFilterModel Filter { get; set; }
        bool IEquatable<ICustomerPaginationRequestModel>.Equals(ICustomerPaginationRequestModel other)
        {
            var result = PageNumber.CompareConsideringNulls(other.PageNumber) && Filter.CompareConsideringNulls(other.Filter);
            return result;
        }
    }
}