// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using Communication.Models.PaginationRequests.CustomerPaginationRequest;
using System.Linq;
using Communication.Common;
using Google.Protobuf.Collections;
using System.Collections.Generic;
using System.Collections;
using Communication.ProtoModels.Conversion;
namespace Communication.ProtoModels
{
    public sealed partial class CustomerPaginationRequestModelList : IList<Communication.Models.PaginationRequests.CustomerPaginationRequest.ICustomerPaginationRequestModel>
    {
        internal ListWrapper<CustomerPaginationRequestModel, RepeatedField<CustomerPaginationRequestModel>, ICustomerPaginationRequestModel> Wrapper { get; private set; }
        public CustomerPaginationRequestModelList(RepeatedField<CustomerPaginationRequestModel> itemsParameter)
        {
            this.message_ = itemsParameter;
            OnConstruction();
        }
        partial void OnConstruction()
        {
            Wrapper = new ListWrapper<CustomerPaginationRequestModel, RepeatedField<CustomerPaginationRequestModel>, ICustomerPaginationRequestModel>(Message, i => i.ToProto());
        }
        ICustomerPaginationRequestModel IList<ICustomerPaginationRequestModel>.this[int index] { get => Wrapper[index]; set => Wrapper[index] = value; }
        int IList<ICustomerPaginationRequestModel>.IndexOf(ICustomerPaginationRequestModel item) => Wrapper.IndexOf(item);
        void IList<ICustomerPaginationRequestModel>.Insert(int index, ICustomerPaginationRequestModel item) => Wrapper.Insert(index, item);
        void IList<ICustomerPaginationRequestModel>.RemoveAt(int index) => Wrapper.RemoveAt(index);
        int ICollection<ICustomerPaginationRequestModel>.Count => Wrapper.Count;
        bool ICollection<ICustomerPaginationRequestModel>.IsReadOnly => Wrapper.IsReadOnly;
        void ICollection<ICustomerPaginationRequestModel>.Add(ICustomerPaginationRequestModel item) => Wrapper.Add(item);
        void ICollection<ICustomerPaginationRequestModel>.Clear() => Wrapper.Clear();
        bool ICollection<ICustomerPaginationRequestModel>.Contains(ICustomerPaginationRequestModel item) => Wrapper.Contains(item);
        void ICollection<ICustomerPaginationRequestModel>.CopyTo(ICustomerPaginationRequestModel[] array, int arrayIndex) => Wrapper.CopyTo(array, arrayIndex);
        IEnumerator<ICustomerPaginationRequestModel> IEnumerable<ICustomerPaginationRequestModel>.GetEnumerator() => Wrapper.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => Wrapper.GetEnumerator();
        bool ICollection<ICustomerPaginationRequestModel>.Remove(ICustomerPaginationRequestModel item) => Wrapper.Remove(item);
        public static implicit operator CustomerPaginationRequestModelList(RepeatedField<CustomerPaginationRequestModel> from)
        {
            var result = new CustomerPaginationRequestModelList(from);
            return result;
        }
        public static implicit operator RepeatedField<CustomerPaginationRequestModel>(CustomerPaginationRequestModelList from)
        {
            return from.Message;
        }
    }
    public sealed partial class CustomerPaginationRequestModel : ICustomerPaginationRequestModel
    {
        Communication.Models.Filters.CustomerModelFilter.ICustomerModelFilterModel ICustomerPaginationRequestModel.Filter
        {
            set
            {
                Filter = value.ToProto();
            }
            get
            {
                return Filter;
            }
        }
    }
}