// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System.Linq;
using System;
using System.Collections.Generic;
using Data;
using Data.Entities.Documents;
using Communication.Models.Entities.ReferrableEntities.Documents.OutcomingOrder;
using System.Linq.Expressions;
namespace Business.Selectors
{
    public static partial class OutcomingOrderSelectors
    {
        public static Expression<Func<OutcomingOrder, IOutcomingOrderModel>> ModelSelector(ApplicationDbContext dbContext) => e1 => new OutcomingOrderModel{Number = e1.Number, // Referring properties.
        Reference = dbContext.OutcomingOrders.Where(e2 => e2 == e1).Select(OutcomingOrderSelectors.ReferenceSelector).FirstOrDefault(), OrdersIncoming = e1.OrdersIncoming.AsQueryable().Select(IncomingOrderSelectors.ReferenceSelector).ToList(), };
    }
}