// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
namespace Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier
{
    public interface ISupplierReference : Communication.Models.IReference<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierModel>, IEquatable<ISupplierReference>
    {
        bool IEquatable<ISupplierReference>.Equals(ISupplierReference other)
        {
            return ID == other.ID;
        }
    }
}