// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
using System.Linq;
using Common.Extensions.Object;
namespace Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier
{
    public interface ISupplierModel : Communication.Models.IModelBase, IEquatable<ISupplierModel>
    {
        public System.String Name { get; set; }
        public Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference Reference { get; }
        bool IEquatable<ISupplierModel>.Equals(ISupplierModel other)
        {
            var result = Name.CompareConsideringNulls(other.Name) && Reference.CompareConsideringNulls(other.Reference);
            return result;
        }
    }
}