// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System.Linq;
using Communication.Common;
using Google.Protobuf.Collections;
using System.Collections.Generic;
using Communication.ProtoModels.Conversion;
using System.Collections;
using Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier;
namespace Communication.ProtoModels
{
    public sealed partial class SupplierReference : Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference
    {
        public static implicit operator SupplierReferenceMessage(SupplierReference message)
        {
            return new()
            {Message = message};
        }
        public static implicit operator SupplierReference(SupplierReferenceMessage message)
        {
            return message.Message;
        }
    }
    public sealed partial class SupplierReferenceList : IList<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference>
    {
        internal ListWrapper<SupplierReference, RepeatedField<SupplierReference>, ISupplierReference> Wrapper { get; private set; }
        public SupplierReferenceList(RepeatedField<SupplierReference> itemsParameter)
        {
            message_ = itemsParameter;
            OnConstruction();
        }
        partial void OnConstruction()
        {
            Wrapper = new ListWrapper<SupplierReference, RepeatedField<SupplierReference>, ISupplierReference>(Message, i => i.ToProto());
        }
        Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference IList<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference>.this[int index] { get => Wrapper[index]; set => Wrapper[index] = value; }
        int IList<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference>.IndexOf(Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference item) => Wrapper.IndexOf(item);
        void IList<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference>.Insert(int index, Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference item) => Wrapper.Insert(index, item);
        void IList<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference>.RemoveAt(int index) => Wrapper.RemoveAt(index);
        int ICollection<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference>.Count => Wrapper.Count;
        bool ICollection<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference>.IsReadOnly => Wrapper.IsReadOnly;
        void ICollection<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference>.Add(Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference item) => Wrapper.Add(item);
        void ICollection<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference>.Clear() => Wrapper.Clear();
        bool ICollection<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference>.Contains(Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference item) => Wrapper.Contains(item);
        void ICollection<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference>.CopyTo(Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference[] array, int arrayIndex) => Wrapper.CopyTo(array, arrayIndex);
        IEnumerator<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference> IEnumerable<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference>.GetEnumerator() => Wrapper.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => Wrapper.GetEnumerator();
        bool ICollection<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference>.Remove(Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference item) => Wrapper.Remove(item);
    }
}