// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier
{
    public class SupplierReference : Communication.Models.Reference<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierModel>, Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference
    {
        public override bool Equals(object other)
        {
            return other is ISupplierReference rightType && rightType.ID == ID;
        }
    }
}