// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier
{
    public partial class SupplierModel : Communication.Models.ModelBase, Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierModel
    {
        public override string ToString()
        {
            return this.Reference?.Representation ?? base.ToString();
        }
        public System.String Name { get; set; }
        public Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.ISupplierReference Reference { get; set; } = new Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier.SupplierReference();
    }
}