// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Entities.ReferrableEntities.DataHolders.Good
{
    public partial class GoodModel : Communication.Models.ModelBase, Communication.Models.Entities.ReferrableEntities.DataHolders.Good.IGoodModel
    {
        public override string ToString()
        {
            return this.Reference?.Representation ?? base.ToString();
        }
        public System.String Name { get; set; }
        public Communication.Models.Entities.ReferrableEntities.DataHolders.Good.IGoodReference Reference { get; set; } = new Communication.Models.Entities.ReferrableEntities.DataHolders.Good.GoodReference();
        public System.Collections.Generic.IList<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference> ResponsibleEmployees { get; set; } = new System.Collections.Generic.List<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference>();
    }
}