// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
namespace Communication.Models.Entities.ReferrableEntities.DataHolders.Good
{
    public interface IGoodReference : Communication.Models.IReference<Communication.Models.Entities.ReferrableEntities.DataHolders.Good.IGoodModel>, IEquatable<IGoodReference>
    {
        bool IEquatable<IGoodReference>.Equals(IGoodReference other)
        {
            return ID == other.ID;
        }
    }
}