// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Filters.DateTimeFilter
{
    public partial class DateTimeFilterModel : Communication.Models.ModelBase, Communication.Models.Filters.DateTimeFilter.IDateTimeFilterModel
    {
        public System.DateTime LeftLimit { get; set; }
        public System.DateTime RightLimit { get; set; }
        public System.Boolean Exclusive { get; set; }
        public System.UInt32 Limit { get; set; }
    }
}