// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
using System.Linq;
using Common.Extensions.Object;
namespace Communication.Models.Filters.DateTimeFilter
{
    public interface IDateTimeFilterModel : Communication.Models.IModelBase, IEquatable<IDateTimeFilterModel>
    {
        public System.DateTime LeftLimit { get; }
        public System.DateTime RightLimit { get; }
        public System.Boolean Exclusive { get; }
        public System.UInt32 Limit { get; }
        bool IEquatable<IDateTimeFilterModel>.Equals(IDateTimeFilterModel other)
        {
            var result = LeftLimit.CompareConsideringNulls(other.LeftLimit) && RightLimit.CompareConsideringNulls(other.RightLimit) && Exclusive.CompareConsideringNulls(other.Exclusive) && Limit.CompareConsideringNulls(other.Limit);
            return result;
        }
    }
}