// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.PaginationRequests.EmployeePaginationRequest
{
    public partial class EmployeePaginationRequestModel : Communication.Models.ModelBase, Communication.Models.PaginationRequests.EmployeePaginationRequest.IEmployeePaginationRequestModel
    {
        public System.UInt32 PageNumber { get; set; }
        public Communication.Models.Filters.EmployeeModelFilter.IEmployeeModelFilterModel Filter { get; set; } = new Communication.Models.Filters.EmployeeModelFilter.EmployeeModelFilterModel();
    }
}