// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
using System.Linq;
using Common.Extensions.Object;
namespace Communication.Models.PaginationRequests.EmployeePaginationRequest
{
    public interface IEmployeePaginationRequestModel : Communication.Models.IModelBase, IEquatable<IEmployeePaginationRequestModel>
    {
        public System.UInt32 PageNumber { get; }
        public Communication.Models.Filters.EmployeeModelFilter.IEmployeeModelFilterModel Filter { get; set; }
        bool IEquatable<IEmployeePaginationRequestModel>.Equals(IEmployeePaginationRequestModel other)
        {
            var result = PageNumber.CompareConsideringNulls(other.PageNumber) && Filter.CompareConsideringNulls(other.Filter);
            return result;
        }
    }
}