// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using Communication.Models.PaginationRequests.EmployeePaginationRequest;
using System.Linq;
using Communication.Common;
using Google.Protobuf.Collections;
using System.Collections.Generic;
using System.Collections;
using Communication.ProtoModels.Conversion;
namespace Communication.ProtoModels
{
    public sealed partial class EmployeePaginationRequestModelList : IList<Communication.Models.PaginationRequests.EmployeePaginationRequest.IEmployeePaginationRequestModel>
    {
        internal ListWrapper<EmployeePaginationRequestModel, RepeatedField<EmployeePaginationRequestModel>, IEmployeePaginationRequestModel> Wrapper { get; private set; }
        public EmployeePaginationRequestModelList(RepeatedField<EmployeePaginationRequestModel> itemsParameter)
        {
            this.message_ = itemsParameter;
            OnConstruction();
        }
        partial void OnConstruction()
        {
            Wrapper = new ListWrapper<EmployeePaginationRequestModel, RepeatedField<EmployeePaginationRequestModel>, IEmployeePaginationRequestModel>(Message, i => i.ToProto());
        }
        IEmployeePaginationRequestModel IList<IEmployeePaginationRequestModel>.this[int index] { get => Wrapper[index]; set => Wrapper[index] = value; }
        int IList<IEmployeePaginationRequestModel>.IndexOf(IEmployeePaginationRequestModel item) => Wrapper.IndexOf(item);
        void IList<IEmployeePaginationRequestModel>.Insert(int index, IEmployeePaginationRequestModel item) => Wrapper.Insert(index, item);
        void IList<IEmployeePaginationRequestModel>.RemoveAt(int index) => Wrapper.RemoveAt(index);
        int ICollection<IEmployeePaginationRequestModel>.Count => Wrapper.Count;
        bool ICollection<IEmployeePaginationRequestModel>.IsReadOnly => Wrapper.IsReadOnly;
        void ICollection<IEmployeePaginationRequestModel>.Add(IEmployeePaginationRequestModel item) => Wrapper.Add(item);
        void ICollection<IEmployeePaginationRequestModel>.Clear() => Wrapper.Clear();
        bool ICollection<IEmployeePaginationRequestModel>.Contains(IEmployeePaginationRequestModel item) => Wrapper.Contains(item);
        void ICollection<IEmployeePaginationRequestModel>.CopyTo(IEmployeePaginationRequestModel[] array, int arrayIndex) => Wrapper.CopyTo(array, arrayIndex);
        IEnumerator<IEmployeePaginationRequestModel> IEnumerable<IEmployeePaginationRequestModel>.GetEnumerator() => Wrapper.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => Wrapper.GetEnumerator();
        bool ICollection<IEmployeePaginationRequestModel>.Remove(IEmployeePaginationRequestModel item) => Wrapper.Remove(item);
        public static implicit operator EmployeePaginationRequestModelList(RepeatedField<EmployeePaginationRequestModel> from)
        {
            var result = new EmployeePaginationRequestModelList(from);
            return result;
        }
        public static implicit operator RepeatedField<EmployeePaginationRequestModel>(EmployeePaginationRequestModelList from)
        {
            return from.Message;
        }
    }
    public sealed partial class EmployeePaginationRequestModel : IEmployeePaginationRequestModel
    {
        Communication.Models.Filters.EmployeeModelFilter.IEmployeeModelFilterModel IEmployeePaginationRequestModel.Filter
        {
            set
            {
                Filter = value.ToProto();
            }
            get
            {
                return Filter;
            }
        }
    }
}