// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models
{
    public partial interface IReference
    {
        public System.UInt32 ID { get; set; }
        public System.String Representation { get; set; }
        public bool Empty => ID == 0;
    }
    public partial interface IReference<TModel> : Communication.Models.IReference where TModel : Communication.Models.IModelBase
    {
    }
}