// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models
{
    public partial class Reference : Communication.Models.IReference
    {
        public System.UInt32 ID { get; set; }
        public System.String Representation { get; set; }
        public override string ToString()
        {
            return Representation;
        }
    }
    public partial class Reference<TModel> : Communication.Models.Reference, Communication.Models.IReference<TModel> where TModel : Communication.Models.IModelBase
    {
    }
}