// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
using System.Linq;
using Common.Extensions.Object;
namespace Communication.Models.Filters.NumberFilter
{
    public interface INumberFilterModel : Communication.Models.IModelBase, IEquatable<INumberFilterModel>
    {
        public System.Single LeftLimit { get; }
        public System.Single RightLimit { get; }
        public System.Boolean Exclusive { get; }
        public System.UInt32 Limit { get; }
        bool IEquatable<INumberFilterModel>.Equals(INumberFilterModel other)
        {
            var result = LeftLimit.CompareConsideringNulls(other.LeftLimit) && RightLimit.CompareConsideringNulls(other.RightLimit) && Exclusive.CompareConsideringNulls(other.Exclusive) && Limit.CompareConsideringNulls(other.Limit);
            return result;
        }
    }
}