// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Filters.NumberFilter
{
    public partial class NumberFilterModel : Communication.Models.ModelBase, Communication.Models.Filters.NumberFilter.INumberFilterModel
    {
        public System.Single LeftLimit { get; set; }
        public System.Single RightLimit { get; set; }
        public System.Boolean Exclusive { get; set; }
        public System.UInt32 Limit { get; set; }
    }
}