// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System.Linq;
using System;
using System.Collections.Generic;
using Data;
using Data.Entities.DataHolders.Actors;
using Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Customer;
using System.Linq.Expressions;
namespace Business.Selectors
{
    public static partial class CustomerSelectors
    {
        public static Expression<Func<Customer, ICustomerModel>> ModelSelector(ApplicationDbContext dbContext) => e1 => new CustomerModel{Name = e1.Name, // Referring properties.
        Reference = dbContext.Customers.Where(e2 => e2 == e1).Select(CustomerSelectors.ReferenceSelector).FirstOrDefault(), };
    }
}