// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using Communication.ProtoModels;
using System.Linq;
using System;
using System.Collections.Generic;
using Data;
using Data.Entities.DataHolders.Actors;
using Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Customer;
using System.Linq.Expressions;
namespace Business.Selectors
{
    public static partial class CustomerSelectors
    {
        public static readonly Expression<Func<Customer, ICustomerReference>> ReferenceSelector = e1 => new Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Customer.CustomerReference{ID = e1.ID, Representation = e1.Representation};
    }
}