// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System.Linq;
using System;
using System.Collections.Generic;
using Data;
using Data.Entities.DataHolders;
using Communication.Models.Entities.ReferrableEntities.DataHolders.Good;
using System.Linq.Expressions;
namespace Business.Selectors
{
    public static partial class GoodSelectors
    {
        public static Expression<Func<Good, IGoodModel>> ModelSelector(ApplicationDbContext dbContext) => e1 => new GoodModel{Name = e1.Name, // Referring properties.
        Reference = dbContext.Goods.Where(e2 => e2 == e1).Select(GoodSelectors.ReferenceSelector).FirstOrDefault(), ResponsibleEmployees = e1.ResponsibleEmployees.AsQueryable().Select(EmployeeSelectors.ReferenceSelector).ToList(), };
    }
}