// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using Communication.ProtoModels;
using System.Linq;
using System;
using System.Collections.Generic;
using Data;
using Data.Entities.DataHolders;
using Communication.Models.Entities.ReferrableEntities.DataHolders.Good;
using System.Linq.Expressions;
namespace Business.Selectors
{
    public static partial class GoodSelectors
    {
        public static readonly Expression<Func<Good, IGoodReference>> ReferenceSelector = e1 => new Communication.Models.Entities.ReferrableEntities.DataHolders.Good.GoodReference{ID = e1.ID, Representation = e1.Representation};
    }
}