// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Filters.StringFilter
{
    public partial class StringFilterModel : Communication.Models.ModelBase, Communication.Models.Filters.StringFilter.IStringFilterModel
    {
        public System.String Pattern { get; set; }
        public System.Boolean Exclusive { get; set; }
        public System.UInt32 Limit { get; set; }
    }
}