// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee
{
    public partial class EmployeeModel : Communication.Models.ModelBase, Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeModel
    {
        public override string ToString()
        {
            return this.Reference?.Representation ?? base.ToString();
        }
        public System.String FirstName { get; set; }
        public System.String LastName { get; set; }
        public Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference Reference { get; set; } = new Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.EmployeeReference();
        public Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference Mentor { get; set; } = new Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.EmployeeReference();
        public System.Collections.Generic.IList<Communication.Models.Entities.ReferrableEntities.DataHolders.Good.IGoodReference> ResponsibleForGoods { get; set; } = new System.Collections.Generic.List<Communication.Models.Entities.ReferrableEntities.DataHolders.Good.IGoodReference>();
    }
}