// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
namespace Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee
{
    public interface IEmployeeReference : Communication.Models.IReference<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeModel>, IEquatable<IEmployeeReference>
    {
        bool IEquatable<IEmployeeReference>.Equals(IEmployeeReference other)
        {
            return ID == other.ID;
        }
    }
}