// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System.Linq;
using Communication.Common;
using Google.Protobuf.Collections;
using System.Collections.Generic;
using Communication.ProtoModels.Conversion;
using System.Collections;
using Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee;
namespace Communication.ProtoModels
{
    public sealed partial class EmployeeReference : Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference
    {
        public static implicit operator EmployeeReferenceMessage(EmployeeReference message)
        {
            return new()
            {Message = message};
        }
        public static implicit operator EmployeeReference(EmployeeReferenceMessage message)
        {
            return message.Message;
        }
    }
    public sealed partial class EmployeeReferenceList : IList<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference>
    {
        internal ListWrapper<EmployeeReference, RepeatedField<EmployeeReference>, IEmployeeReference> Wrapper { get; private set; }
        public EmployeeReferenceList(RepeatedField<EmployeeReference> itemsParameter)
        {
            message_ = itemsParameter;
            OnConstruction();
        }
        partial void OnConstruction()
        {
            Wrapper = new ListWrapper<EmployeeReference, RepeatedField<EmployeeReference>, IEmployeeReference>(Message, i => i.ToProto());
        }
        Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference IList<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference>.this[int index] { get => Wrapper[index]; set => Wrapper[index] = value; }
        int IList<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference>.IndexOf(Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference item) => Wrapper.IndexOf(item);
        void IList<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference>.Insert(int index, Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference item) => Wrapper.Insert(index, item);
        void IList<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference>.RemoveAt(int index) => Wrapper.RemoveAt(index);
        int ICollection<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference>.Count => Wrapper.Count;
        bool ICollection<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference>.IsReadOnly => Wrapper.IsReadOnly;
        void ICollection<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference>.Add(Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference item) => Wrapper.Add(item);
        void ICollection<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference>.Clear() => Wrapper.Clear();
        bool ICollection<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference>.Contains(Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference item) => Wrapper.Contains(item);
        void ICollection<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference>.CopyTo(Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference[] array, int arrayIndex) => Wrapper.CopyTo(array, arrayIndex);
        IEnumerator<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference> IEnumerable<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference>.GetEnumerator() => Wrapper.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => Wrapper.GetEnumerator();
        bool ICollection<Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference>.Remove(Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.IEmployeeReference item) => Wrapper.Remove(item);
    }
}