// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Filters.IncomingOrderLineModelFilter
{
    public partial class IncomingOrderLineModelFilterModel : Communication.Models.ModelBase, Communication.Models.Filters.IncomingOrderLineModelFilter.IIncomingOrderLineModelFilterModel
    {
        public System.Boolean Exclusive { get; set; }
        public System.UInt32 Limit { get; set; }
        public Communication.Models.Filters.NumberFilter.INumberFilterModel Quantity { get; set; }
        public Communication.Models.Filters.NumberFilter.INumberFilterModel Price { get; set; }
        public Communication.Models.Filters.ReferenceFilter.IReferenceFilterModel IncomingOrder { get; set; }
        public Communication.Models.Filters.ReferenceFilter.IReferenceFilterModel Good { get; set; }
    }
}