// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using Communication.ProtoModels;
using System.Linq;
using System;
using System.Collections.Generic;
using Data;
using Data.Entities.DataHolders;
using Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee;
using System.Linq.Expressions;
namespace Business.Selectors
{
    public static partial class EmployeeSelectors
    {
        public static readonly Expression<Func<Employee, IEmployeeReference>> ReferenceSelector = e1 => new Communication.Models.Entities.ReferrableEntities.DataHolders.Persons.Employee.EmployeeReference{ID = e1.ID, Representation = e1.Representation};
    }
}