// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
using System.Linq;
using Common.Extensions.Object;
namespace Communication.Models.PaginationRequests.OutcomingOrderPaginationRequest
{
    public interface IOutcomingOrderPaginationRequestModel : Communication.Models.IModelBase, IEquatable<IOutcomingOrderPaginationRequestModel>
    {
        public System.UInt32 PageNumber { get; }
        public Communication.Models.Filters.OutcomingOrderModelFilter.IOutcomingOrderModelFilterModel Filter { get; set; }
        bool IEquatable<IOutcomingOrderPaginationRequestModel>.Equals(IOutcomingOrderPaginationRequestModel other)
        {
            var result = PageNumber.CompareConsideringNulls(other.PageNumber) && Filter.CompareConsideringNulls(other.Filter);
            return result;
        }
    }
}