// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using Communication.Models.PaginationRequests.OutcomingOrderPaginationRequest;
using System.Linq;
using Communication.Common;
using Google.Protobuf.Collections;
using System.Collections.Generic;
using System.Collections;
using Communication.ProtoModels.Conversion;
namespace Communication.ProtoModels
{
    public sealed partial class OutcomingOrderPaginationRequestModelList : IList<Communication.Models.PaginationRequests.OutcomingOrderPaginationRequest.IOutcomingOrderPaginationRequestModel>
    {
        internal ListWrapper<OutcomingOrderPaginationRequestModel, RepeatedField<OutcomingOrderPaginationRequestModel>, IOutcomingOrderPaginationRequestModel> Wrapper { get; private set; }
        public OutcomingOrderPaginationRequestModelList(RepeatedField<OutcomingOrderPaginationRequestModel> itemsParameter)
        {
            this.message_ = itemsParameter;
            OnConstruction();
        }
        partial void OnConstruction()
        {
            Wrapper = new ListWrapper<OutcomingOrderPaginationRequestModel, RepeatedField<OutcomingOrderPaginationRequestModel>, IOutcomingOrderPaginationRequestModel>(Message, i => i.ToProto());
        }
        IOutcomingOrderPaginationRequestModel IList<IOutcomingOrderPaginationRequestModel>.this[int index] { get => Wrapper[index]; set => Wrapper[index] = value; }
        int IList<IOutcomingOrderPaginationRequestModel>.IndexOf(IOutcomingOrderPaginationRequestModel item) => Wrapper.IndexOf(item);
        void IList<IOutcomingOrderPaginationRequestModel>.Insert(int index, IOutcomingOrderPaginationRequestModel item) => Wrapper.Insert(index, item);
        void IList<IOutcomingOrderPaginationRequestModel>.RemoveAt(int index) => Wrapper.RemoveAt(index);
        int ICollection<IOutcomingOrderPaginationRequestModel>.Count => Wrapper.Count;
        bool ICollection<IOutcomingOrderPaginationRequestModel>.IsReadOnly => Wrapper.IsReadOnly;
        void ICollection<IOutcomingOrderPaginationRequestModel>.Add(IOutcomingOrderPaginationRequestModel item) => Wrapper.Add(item);
        void ICollection<IOutcomingOrderPaginationRequestModel>.Clear() => Wrapper.Clear();
        bool ICollection<IOutcomingOrderPaginationRequestModel>.Contains(IOutcomingOrderPaginationRequestModel item) => Wrapper.Contains(item);
        void ICollection<IOutcomingOrderPaginationRequestModel>.CopyTo(IOutcomingOrderPaginationRequestModel[] array, int arrayIndex) => Wrapper.CopyTo(array, arrayIndex);
        IEnumerator<IOutcomingOrderPaginationRequestModel> IEnumerable<IOutcomingOrderPaginationRequestModel>.GetEnumerator() => Wrapper.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => Wrapper.GetEnumerator();
        bool ICollection<IOutcomingOrderPaginationRequestModel>.Remove(IOutcomingOrderPaginationRequestModel item) => Wrapper.Remove(item);
        public static implicit operator OutcomingOrderPaginationRequestModelList(RepeatedField<OutcomingOrderPaginationRequestModel> from)
        {
            var result = new OutcomingOrderPaginationRequestModelList(from);
            return result;
        }
        public static implicit operator RepeatedField<OutcomingOrderPaginationRequestModel>(OutcomingOrderPaginationRequestModelList from)
        {
            return from.Message;
        }
    }
    public sealed partial class OutcomingOrderPaginationRequestModel : IOutcomingOrderPaginationRequestModel
    {
        Communication.Models.Filters.OutcomingOrderModelFilter.IOutcomingOrderModelFilterModel IOutcomingOrderPaginationRequestModel.Filter
        {
            set
            {
                Filter = value.ToProto();
            }
            get
            {
                return Filter;
            }
        }
    }
}