// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.PaginationRequests.OutcomingOrderPaginationRequest
{
    public partial class OutcomingOrderPaginationRequestModel : Communication.Models.ModelBase, Communication.Models.PaginationRequests.OutcomingOrderPaginationRequest.IOutcomingOrderPaginationRequestModel
    {
        public System.UInt32 PageNumber { get; set; }
        public Communication.Models.Filters.OutcomingOrderModelFilter.IOutcomingOrderModelFilterModel Filter { get; set; } = new Communication.Models.Filters.OutcomingOrderModelFilter.OutcomingOrderModelFilterModel();
    }
}