// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Filters.BooleanFilter
{
    public partial class BooleanFilterModel : Communication.Models.ModelBase, Communication.Models.Filters.BooleanFilter.IBooleanFilterModel
    {
        public System.Boolean Value { get; set; }
        public System.Boolean Exclusive { get; set; }
        public System.UInt32 Limit { get; set; }
    }
}