// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
using System.Linq;
using Common.Extensions.Object;
namespace Communication.Models.Filters.BooleanFilter
{
    public interface IBooleanFilterModel : Communication.Models.IModelBase, IEquatable<IBooleanFilterModel>
    {
        public System.Boolean Value { get; }
        public System.Boolean Exclusive { get; }
        public System.UInt32 Limit { get; }
        bool IEquatable<IBooleanFilterModel>.Equals(IBooleanFilterModel other)
        {
            var result = Value.CompareConsideringNulls(other.Value) && Exclusive.CompareConsideringNulls(other.Exclusive) && Limit.CompareConsideringNulls(other.Limit);
            return result;
        }
    }
}