// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
using System.Linq;
namespace Web.Client.Services
{
    public class ActionStatus<TResponseType>
    {
        public bool IsUnderway;
        public TResponseType Response;
        public Exception Error;
    }
}