// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System.Linq;
using System;
using System.Collections.Generic;
using Data;
using Data.Entities.DataHolders.Actors;
using Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Supplier;
using System.Linq.Expressions;
namespace Business.Selectors
{
    public static partial class SupplierSelectors
    {
        public static Expression<Func<Supplier, ISupplierModel>> ModelSelector(ApplicationDbContext dbContext) => e1 => new SupplierModel{Name = e1.Name, // Referring properties.
        Reference = dbContext.Suppliers.Where(e2 => e2 == e1).Select(SupplierSelectors.ReferenceSelector).FirstOrDefault(), };
    }
}