// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
using System.Linq;
using Common.Extensions.Object;
namespace Communication.Models.PaginationRequests.IncomingOrderLinePaginationRequest
{
    public interface IIncomingOrderLinePaginationRequestModel : Communication.Models.IModelBase, IEquatable<IIncomingOrderLinePaginationRequestModel>
    {
        public System.UInt32 PageNumber { get; }
        public Communication.Models.Filters.IncomingOrderLineModelFilter.IIncomingOrderLineModelFilterModel Filter { get; set; }
        bool IEquatable<IIncomingOrderLinePaginationRequestModel>.Equals(IIncomingOrderLinePaginationRequestModel other)
        {
            var result = PageNumber.CompareConsideringNulls(other.PageNumber) && Filter.CompareConsideringNulls(other.Filter);
            return result;
        }
    }
}