// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Entities.ReferrableEntities.Documents.OutcomingOrder
{
    public partial class OutcomingOrderModel : Communication.Models.ModelBase, Communication.Models.Entities.ReferrableEntities.Documents.OutcomingOrder.IOutcomingOrderModel
    {
        public override string ToString()
        {
            return this.Reference?.Representation ?? base.ToString();
        }
        public System.String Number { get; set; }
        public Communication.Models.Entities.ReferrableEntities.Documents.OutcomingOrder.IOutcomingOrderReference Reference { get; set; } = new Communication.Models.Entities.ReferrableEntities.Documents.OutcomingOrder.OutcomingOrderReference();
        public System.Collections.Generic.IList<Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder.IIncomingOrderReference> OrdersIncoming { get; set; } = new System.Collections.Generic.List<Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder.IIncomingOrderReference>();
    }
}