// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Customer
{
    public partial class CustomerModel : Communication.Models.ModelBase, Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Customer.ICustomerModel
    {
        public override string ToString()
        {
            return this.Reference?.Representation ?? base.ToString();
        }
        public System.String Name { get; set; }
        public Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Customer.ICustomerReference Reference { get; set; } = new Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Customer.CustomerReference();
    }
}