// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Customer
{
    public class CustomerReference : Communication.Models.Reference<Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Customer.ICustomerModel>, Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Customer.ICustomerReference
    {
        public override bool Equals(object other)
        {
            return other is ICustomerReference rightType && rightType.ID == ID;
        }
    }
}