// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
using System.Linq;
using Common.Extensions.Object;
namespace Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Customer
{
    public interface ICustomerModel : Communication.Models.IModelBase, IEquatable<ICustomerModel>
    {
        public System.String Name { get; set; }
        public Communication.Models.Entities.ReferrableEntities.DataHolders.Counterparties.Customer.ICustomerReference Reference { get; }
        bool IEquatable<ICustomerModel>.Equals(ICustomerModel other)
        {
            var result = Name.CompareConsideringNulls(other.Name) && Reference.CompareConsideringNulls(other.Reference);
            return result;
        }
    }
}