// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Data.CommunicationContracts.Pagination
{
    public class CustomerPaginationRequest : Data.CommunicationContracts.PaginationRequest
    {
        public Data.CommunicationContracts.CustomerModelFilter Filter { get; }
    }
}