// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Data.CommunicationContracts.Pagination
{
    public class EmployeePaginationRequest : Data.CommunicationContracts.PaginationRequest
    {
        public Data.CommunicationContracts.EmployeeModelFilter Filter { get; }
    }
}