// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Data.CommunicationContracts.Pagination
{
    public class GoodPaginationRequest : Data.CommunicationContracts.PaginationRequest
    {
        public Data.CommunicationContracts.GoodModelFilter Filter { get; }
    }
}