// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Data.CommunicationContracts.Pagination
{
    public class OutcomingOrderPaginationRequest : Data.CommunicationContracts.PaginationRequest
    {
        public Data.CommunicationContracts.OutcomingOrderModelFilter Filter { get; }
    }
}