// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Data.CommunicationContracts.Pagination
{
    public class SupplierPaginationRequest : Data.CommunicationContracts.PaginationRequest
    {
        public Data.CommunicationContracts.SupplierModelFilter Filter { get; }
    }
}