// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.PaginationRequests.GoodPaginationRequest
{
    public partial class GoodPaginationRequestModel : Communication.Models.ModelBase, Communication.Models.PaginationRequests.GoodPaginationRequest.IGoodPaginationRequestModel
    {
        public System.UInt32 PageNumber { get; set; }
        public Communication.Models.Filters.GoodModelFilter.IGoodModelFilterModel Filter { get; set; } = new Communication.Models.Filters.GoodModelFilter.GoodModelFilterModel();
    }
}