// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
using System.Linq;
using Common.Extensions.Object;
namespace Communication.Models.PaginationRequests.GoodPaginationRequest
{
    public interface IGoodPaginationRequestModel : Communication.Models.IModelBase, IEquatable<IGoodPaginationRequestModel>
    {
        public System.UInt32 PageNumber { get; }
        public Communication.Models.Filters.GoodModelFilter.IGoodModelFilterModel Filter { get; set; }
        bool IEquatable<IGoodPaginationRequestModel>.Equals(IGoodPaginationRequestModel other)
        {
            var result = PageNumber.CompareConsideringNulls(other.PageNumber) && Filter.CompareConsideringNulls(other.Filter);
            return result;
        }
    }
}