// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.PaginationRequests.IncomingOrderPaginationRequest
{
    public partial class IncomingOrderPaginationRequestModel : Communication.Models.ModelBase, Communication.Models.PaginationRequests.IncomingOrderPaginationRequest.IIncomingOrderPaginationRequestModel
    {
        public System.UInt32 PageNumber { get; set; }
        public Communication.Models.Filters.IncomingOrderModelFilter.IIncomingOrderModelFilterModel Filter { get; set; } = new Communication.Models.Filters.IncomingOrderModelFilter.IncomingOrderModelFilterModel();
    }
}