// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
using System.Linq;
using Common.Extensions.Object;
namespace Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder
{
    public interface IIncomingOrderModel : Communication.Models.IModelBase, IEquatable<IIncomingOrderModel>
    {
        public System.String Number { get; set; }
        public Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder.IIncomingOrderReference Reference { get; }
        public System.Collections.Generic.IList<Communication.Models.Entities.TableLines.GoodTransactionLines.IncomingOrderLine.IIncomingOrderLineModel> RequestedGoods { get; }
        bool IEquatable<IIncomingOrderModel>.Equals(IIncomingOrderModel other)
        {
            var result = Number.CompareConsideringNulls(other.Number) && Reference.CompareConsideringNulls(other.Reference) && RequestedGoods.Count == other.RequestedGoods.Count && RequestedGoods.All(p1 => other.RequestedGoods.Any(p2 => p1.CompareConsideringNulls(p2)));
            return result;
        }
    }
}