// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
namespace Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder
{
    public interface IIncomingOrderReference : Communication.Models.IReference<Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder.IIncomingOrderModel>, IEquatable<IIncomingOrderReference>
    {
        bool IEquatable<IIncomingOrderReference>.Equals(IIncomingOrderReference other)
        {
            return ID == other.ID;
        }
    }
}