// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder
{
    public partial class IncomingOrderModel : Communication.Models.ModelBase, Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder.IIncomingOrderModel
    {
        public override string ToString()
        {
            return this.Reference?.Representation ?? base.ToString();
        }
        public System.String Number { get; set; }
        public Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder.IIncomingOrderReference Reference { get; set; } = new Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder.IncomingOrderReference();
        public System.Collections.Generic.IList<Communication.Models.Entities.TableLines.GoodTransactionLines.IncomingOrderLine.IIncomingOrderLineModel> RequestedGoods { get; set; } = new System.Collections.Generic.List<Communication.Models.Entities.TableLines.GoodTransactionLines.IncomingOrderLine.IIncomingOrderLineModel>();
    }
}