// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Filters.IncomingOrderModelFilter
{
    public partial class IncomingOrderModelFilterModel : Communication.Models.ModelBase, Communication.Models.Filters.IncomingOrderModelFilter.IIncomingOrderModelFilterModel
    {
        public System.Boolean Exclusive { get; set; }
        public System.UInt32 Limit { get; set; }
        public Communication.Models.Filters.StringFilter.IStringFilterModel Number { get; set; }
        public Communication.Models.Filters.ReferenceFilter.IReferenceFilterModel Reference { get; set; }
        public Communication.Models.Filters.CollectionFilter.ICollectionFilterModel RequestedGoods { get; set; }
    }
}