// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using SourceGeneration.Attributes.Data.Entity;
namespace Data.CommunicationContracts
{
    public class CustomerModelFilter : Filter, IFilterFor<Data.Entities.DataHolders.Actors.Customer>
    {
        public StringFilter Name { get; }
        public ReferenceFilter Reference { get; }
    }
}