// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using SourceGeneration.Attributes.Data.Entity;
namespace Data.CommunicationContracts
{
    public class IncomingOrderModelFilter : Filter, IFilterFor<Data.Entities.IncomingOrder>
    {
        public StringFilter Number { get; }
        public ReferenceFilter Reference { get; }
        public CollectionFilter RequestedGoods { get; }
    }
}