// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using SourceGeneration.Attributes.Data.Entity;
namespace Data.CommunicationContracts
{
    public class IncomingOrderLineModelFilter : Filter, IFilterFor<Data.Entities.Documents.Trade.IncomingOrderLine>
    {
        public NumberFilter Quantity { get; }
        public NumberFilter Price { get; }
        public ReferenceFilter IncomingOrder { get; }
        public ReferenceFilter Good { get; }
    }
}