// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Entities.TableLines.GoodTransactionLines.IncomingOrderLine
{
    public partial class IncomingOrderLineModel : Communication.Models.ModelBase, Communication.Models.Entities.TableLines.GoodTransactionLines.IncomingOrderLine.IIncomingOrderLineModel
    {
        public System.UInt32 Quantity { get; set; }
        public System.Single Price { get; set; }
        public Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder.IIncomingOrderReference IncomingOrder { get; set; } = new Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder.IncomingOrderReference();
        public Communication.Models.Entities.ReferrableEntities.DataHolders.Good.IGoodReference Good { get; set; } = new Communication.Models.Entities.ReferrableEntities.DataHolders.Good.GoodReference();
    }
}