// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System.Linq;
using System;
using System.Collections.Generic;
using Data;
using Data.Entities.Documents.Trade;
using Communication.Models.Entities.TableLines.GoodTransactionLines.IncomingOrderLine;
using System.Linq.Expressions;
namespace Business.Selectors
{
    public static partial class IncomingOrderLineSelectors
    {
        public static Expression<Func<IncomingOrderLine, IIncomingOrderLineModel>> ModelSelector(ApplicationDbContext dbContext) => e1 => new IncomingOrderLineModel{Quantity = e1.Quantity, Price = e1.Price, // Referring properties.
        IncomingOrder = dbContext.IncomingOrders.Where(e2 => e2 == e1.IncomingOrder).Select(IncomingOrderSelectors.ReferenceSelector).FirstOrDefault() ?? new Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder.IncomingOrderReference(), Good = dbContext.Goods.Where(e2 => e2 == e1.Good).Select(GoodSelectors.ReferenceSelector).FirstOrDefault() ?? new Communication.Models.Entities.ReferrableEntities.DataHolders.Good.GoodReference(), };
    }
}