// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.Filters.CollectionFilter
{
    public partial class CollectionFilterModel : Communication.Models.ModelBase, Communication.Models.Filters.CollectionFilter.ICollectionFilterModel
    {
        public System.Boolean Exclusive { get; set; }
        public System.UInt32 Limit { get; set; }
        public Communication.Models.Filters.NumberFilter.INumberFilterModel Count { get; set; }
    }
}