// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using Communication.Models.Filters.SupplierModelFilter;
using System.Linq;
using Communication.Common;
using Google.Protobuf.Collections;
using System.Collections.Generic;
using System.Collections;
using Communication.ProtoModels.Conversion;
namespace Communication.ProtoModels
{
    public sealed partial class SupplierModelFilterModelList : IList<Communication.Models.Filters.SupplierModelFilter.ISupplierModelFilterModel>
    {
        internal ListWrapper<SupplierModelFilterModel, RepeatedField<SupplierModelFilterModel>, ISupplierModelFilterModel> Wrapper { get; private set; }
        public SupplierModelFilterModelList(RepeatedField<SupplierModelFilterModel> itemsParameter)
        {
            this.message_ = itemsParameter;
            OnConstruction();
        }
        partial void OnConstruction()
        {
            Wrapper = new ListWrapper<SupplierModelFilterModel, RepeatedField<SupplierModelFilterModel>, ISupplierModelFilterModel>(Message, i => i.ToProto());
        }
        ISupplierModelFilterModel IList<ISupplierModelFilterModel>.this[int index] { get => Wrapper[index]; set => Wrapper[index] = value; }
        int IList<ISupplierModelFilterModel>.IndexOf(ISupplierModelFilterModel item) => Wrapper.IndexOf(item);
        void IList<ISupplierModelFilterModel>.Insert(int index, ISupplierModelFilterModel item) => Wrapper.Insert(index, item);
        void IList<ISupplierModelFilterModel>.RemoveAt(int index) => Wrapper.RemoveAt(index);
        int ICollection<ISupplierModelFilterModel>.Count => Wrapper.Count;
        bool ICollection<ISupplierModelFilterModel>.IsReadOnly => Wrapper.IsReadOnly;
        void ICollection<ISupplierModelFilterModel>.Add(ISupplierModelFilterModel item) => Wrapper.Add(item);
        void ICollection<ISupplierModelFilterModel>.Clear() => Wrapper.Clear();
        bool ICollection<ISupplierModelFilterModel>.Contains(ISupplierModelFilterModel item) => Wrapper.Contains(item);
        void ICollection<ISupplierModelFilterModel>.CopyTo(ISupplierModelFilterModel[] array, int arrayIndex) => Wrapper.CopyTo(array, arrayIndex);
        IEnumerator<ISupplierModelFilterModel> IEnumerable<ISupplierModelFilterModel>.GetEnumerator() => Wrapper.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => Wrapper.GetEnumerator();
        bool ICollection<ISupplierModelFilterModel>.Remove(ISupplierModelFilterModel item) => Wrapper.Remove(item);
        public static implicit operator SupplierModelFilterModelList(RepeatedField<SupplierModelFilterModel> from)
        {
            var result = new SupplierModelFilterModelList(from);
            return result;
        }
        public static implicit operator RepeatedField<SupplierModelFilterModel>(SupplierModelFilterModelList from)
        {
            return from.Message;
        }
    }
    public sealed partial class SupplierModelFilterModel : ISupplierModelFilterModel
    {
        Communication.Models.Filters.StringFilter.IStringFilterModel ISupplierModelFilterModel.Name
        {
            set
            {
                Name = value.ToProto();
            }
            get
            {
                return Name;
            }
        }
        Communication.Models.Filters.ReferenceFilter.IReferenceFilterModel ISupplierModelFilterModel.Reference
        {
            set
            {
                Reference = value.ToProto();
            }
            get
            {
                return Reference;
            }
        }
    }
}