// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System;
using System.Linq;
using Common.Extensions.Object;
namespace Communication.Models.PaginationRequests.SupplierPaginationRequest
{
    public interface ISupplierPaginationRequestModel : Communication.Models.IModelBase, IEquatable<ISupplierPaginationRequestModel>
    {
        public System.UInt32 PageNumber { get; }
        public Communication.Models.Filters.SupplierModelFilter.ISupplierModelFilterModel Filter { get; set; }
        bool IEquatable<ISupplierPaginationRequestModel>.Equals(ISupplierPaginationRequestModel other)
        {
            var result = PageNumber.CompareConsideringNulls(other.PageNumber) && Filter.CompareConsideringNulls(other.Filter);
            return result;
        }
    }
}