// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

namespace Communication.Models.PaginationRequests.SupplierPaginationRequest
{
    public partial class SupplierPaginationRequestModel : Communication.Models.ModelBase, Communication.Models.PaginationRequests.SupplierPaginationRequest.ISupplierPaginationRequestModel
    {
        public System.UInt32 PageNumber { get; set; }
        public Communication.Models.Filters.SupplierModelFilter.ISupplierModelFilterModel Filter { get; set; } = new Communication.Models.Filters.SupplierModelFilter.SupplierModelFilterModel();
    }
}