// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using System.Linq;
using System;
using System.Collections.Generic;
using Data;
using Data.Entities;
using Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder;
using System.Linq.Expressions;
namespace Business.Selectors
{
    public static partial class IncomingOrderSelectors
    {
        public static Expression<Func<IncomingOrder, IIncomingOrderModel>> ModelSelector(ApplicationDbContext dbContext) => e1 => new IncomingOrderModel{Number = e1.Number, // Referring properties.
        Reference = dbContext.IncomingOrders.Where(e2 => e2 == e1).Select(IncomingOrderSelectors.ReferenceSelector).FirstOrDefault(), RequestedGoods = e1.RequestedGoods.AsQueryable().Select(IncomingOrderLineSelectors.ModelSelector(dbContext)).ToList(), };
    }
}