// Autogenerated. Will be overwritten on build. Remove this comment to cancel overwriting.

using Communication.ProtoModels;
using System.Linq;
using System;
using System.Collections.Generic;
using Data;
using Data.Entities;
using Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder;
using System.Linq.Expressions;
namespace Business.Selectors
{
    public static partial class IncomingOrderSelectors
    {
        public static readonly Expression<Func<IncomingOrder, IIncomingOrderReference>> ReferenceSelector = e1 => new Communication.Models.Entities.ReferrableEntities.Documents.IncomingOrder.IncomingOrderReference{ID = e1.ID, Representation = e1.Representation};
    }
}